export const UPDATE_MOOVIE_LIST = "UPDATE_MOOVIE_LIST";
export const UPDATE_WATCHED = "UPDATE_WATCHED";
export const UPDATE_LOADING_STATE = "UPDATE_LOADING_STATE";
export const UPDATE_VIEW_ID = "UPDATE_VIEW_ID";

